services:
  web:
    image: node:18-alpine
    ports:
      - "3000:3000"
    volumes:
      - .:/webapp
    working_dir: /webapp
    command: npm run dev
  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      ADMINER_DESIGN: hydra
